python train.py \
    ../data-bin/iwslt14.tokenized.de-en-original \
    --arch transformer_iwslt_de_en \
    --share-all-embeddings \
    --optimizer adam \
    --adam-betas '(0.9, 0.98)' \
    --adam-eps 1e-9 \
    --clip-norm 0.0 \
    --weight-decay 0.0001 \
    --criterion label_smoothed_cross_entropy_with_regularization \
    --label-smoothing 0.1 \
    --max-tokens 4096 \
    --dropout 0.3 \
    --attention-dropout 0.1 \
    --activation-dropout 0.1 \
    --lr-scheduler inverse_sqrt \
    --lr 7e-4 \
    --warmup-updates 6000 \
    --max-epoch 100 \
    --update-freq 1 \
    --save-dir checkpoints_dir/at-baseline-cutoff \
    --seed 10000 \
    --eval-bleu \
    --eval-bleu-args '{"beam": 5, "max_len_a": 1.2, "max_len_b": 10}' \
    --eval-bleu-detok moses \
    --eval-bleu-remove-bpe \
    --eval-tokenized-bleu \
    --best-checkpoint-metric bleu --maximize-best-checkpoint-metric \
    --keep-best-checkpoints 5 \
    --task translation \